version: '3.8'

services:
  sma-mqtt:
    image: unikin/smaem2mqtt
    container_name: sma-mqtt
    environment:
      - MQTT_BROKER=192.168.0.180
      - MQTT_PORT=1883
      - MQTT_TOPIC=sma/data
      - MQTT_USERNAME=new_user
      - MQTT_PASSWORD=new_password
    network_mode: host  # Use the host's network stack for multicast support
    restart: unless-stopped
